version: 1
disable_existing_loggers: False

loggers:
    vio:
      handlers: [vio_handler]
      level: "DEBUG"
      propagate: False
          
handlers:
    vio_handler:
        level: "DEBUG"
        class: "logging.handlers.RotatingFileHandler"
        filename: "/var/log/onap/multicloud/vio/vio.log"
        formatter: "mdcFormat"
        maxBytes: 1024*1024*50
        backupCount: 10    


formatters:
    standard:
        format: "%(asctime)s:[%(name)s]:[%(filename)s]-[%(lineno)d] [%(levelname)s]:%(message)s"
    mdcFormat:
        format: "%(asctime)s:[%(name)s]:[%(filename)s]-[%(lineno)d] [%(levelname)s]:[%(mdc)s]: %(message)s"
        mdcfmt: "{requestID}"
        datefmt: "%Y-%m-%d %H:%M:%S"
        (): onaplogging.mdcformatter.MDCFormatter


